version: "2.1"

services:

  zookeeper:
    hostname: zookeeper
    image: deployable/zookeeper
    restart: always
    ports:
      - 2181
    networks:
     - zoo
    healthcheck:
      test: ["CMD", "/zookeeper/check.sh", "zookeeper" ]
      interval: 15s
      timeout: 5s
      retries: 3

# This is a little bit of a hack to make `up` and `start` not
# return to the shell until `zookeeper` is healthy. So test's
# don't start early

  zookeeper_wait:
    image: deployable/zookeeper
    depends_on:
      zookeeper:
        condition: service_healthy        
    networks:
     - zoo
    environment:
      PORT: 2181
      HOST: zookeeper
    command: [ "/zookeeper/check.sh", "zookeeper" ]
    
networks:
  zoo:
    driver: bridge
  
